Rewrite resource
Qbox-project/qbx_management pull request #16
Opened 2023-11-20 17:10 UTC by solareon

## Description

Rewrite of entire resource to get towards 1.0 release.
- Updated readme with features, dependencies, and installation steps
- Adapted configuration to a combined file in the `require 'config.shared'` format
- Rewrote configuration to reduce redundant code for zone creation
- Rewrote zone setup to match style from QBX_Diving (ox_target and lib.zone support)
- Removed all unneeded Citizen.Thread creation (1 remain for init of boss zones)
- Made all functions local where possible (2 globals for main Boss Menu and Bank Menu)
- Eliminated all network events in favor of callbacks
- Added logging for all relevant functions (hiring, firing, money management)
- Simplified stash registration on startup
- Split online and offline firing of players into separate functions
- Combined separate boss and gang menus into single client script
- Documented all functions, variables, and returns where appropriate
- Removed unneeded SQL files (now handled by core)
- Adjusted fxmanifest to support new config style

## Checklist

- [X] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [X] My code fits the style guidelines.
- [X] My PR fits the contribution guidelines.

2023-11-20 17:36 UTC, Manason requested changes

2023-11-20 17:36 UTC, Manason commented on server/main.lua
> +	local players = MySQL.query.await('SELECT * FROM `players` WHERE ?? LIKE \'%'.. groupName ..'%\'', {group})
The string is already a string format. Don't concatenate in the middle of it, but instead replace strings the same way group is being done

2023-11-20 17:36 UTC, Manason commented on client/main.lua
> +
two spaces?

2023-11-20 17:36 UTC, Manason commented on server/main.lua
> +	local players = MySQL.query.await('SELECT * FROM `players` WHERE ?? LIKE \'%'.. groupName ..'%\'', {group})
Also, I think using double quotes around this string could help with readability

2023-11-20 17:45 UTC, solareon commented on server/main.lua
> +	local players = MySQL.query.await('SELECT * FROM `players` WHERE ?? LIKE \'%'.. groupName ..'%\'', {group})
That's fair. Didn't see anything your style guide on if double quotes or single quotes were preferred so I went on the warpath against double quotes.

2023-11-20 17:46 UTC, solareon commented on client/main.lua
> +
Double tapped the enter key?

2023-11-20 18:04 UTC, Manason commented on server/main.lua
> +	local players = MySQL.query.await('SELECT * FROM `players` WHERE ?? LIKE \'%'.. groupName ..'%\'', {group})
I would say double quotes would normally be preferred, but if you re going to have single quotes inside of them, it makes sense instead of escaping the single quotes

2023-11-20 18:07 UTC, Manason approved these changes

2023-11-21 03:53 UTC, MafewTM approved these changes

2023-11-21 03:54 UTC, merged