feat: storage.lua
Qbox-project/qbx_management pull request #22
Opened 2023-12-03 00:02 UTC by MafewTM

## Description

Implement a storage.lua

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My code fits the style guidelines.
- [ ] My PR fits the contribution guidelines.

2023-12-03 22:20 UTC, Manason requested changes
Feel like we should refer to the database table returned as an Entity to differentiate from the player objects we use in core

2023-12-03 22:20 UTC, Manason commented on server/storage.lua
> +---@param group string
what is the difference between groupName and group?

2023-12-03 22:20 UTC, Manason commented on server/storage.lua
> +function UpdatePlayerJob(column, role, citizenId)
Feels like citizenid should go first as the identifier?

2023-12-03 22:20 UTC, Manason commented on server/storage.lua
> +---@param role string
Maybe role should be passed as a table and then json encoded in this function? Feels like that should happen as late as possible

2023-12-03 22:20 UTC, Manason commented on server/storage.lua
> +---@param column string
```suggestion
---@param column gang | job
```

2023-12-03 22:20 UTC, Manason commented on server/storage.lua
> +function FetchPlayersByGroup(groupName, group)
```suggestion
function FetchPlayerEntitiesByGroup(groupName, group)
```

2023-12-03 22:20 UTC, Manason commented on server/storage.lua
> +function FetchPlayerByCitizenId(citizenId)
```suggestion
function FetchPlayerEntityByCitizenId(citizenId)
```

2023-12-04 21:34 UTC, MafewTM commented on server/storage.lua
> +---@param group string
![image](https://github.com/Qbox-project/qbx_management/assets/22198949/812c176e-1456-492e-b16c-8fcdf7ecc991)

2023-12-04 22:18 UTC, Manason approved these changes

2023-12-04 22:19 UTC, merged