feat: logging module
Qbox-project/qbx_management pull request #23
Opened 2023-12-06 16:28 UTC by MafewTM

## Description

Implements the new logging module and lib.logger to replace the deprecated qb-logs

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My code fits the style guidelines.
- [ ] My PR fits the contribution guidelines.

2023-12-06 17:14 UTC, Manason requested changes

2023-12-06 17:14 UTC, Manason commented on server/main.lua
> +		logger.log({source = source, event = 'hireEmployee', message = string.format('%s | %s hired %s into %s at grade %s', logArea, playerFullName, targetFullName, organizationLabel, grade)})
Should the source be 'qbx_management'?

Also feel we should add a web hook to config that is nil but passed through for those who want discord logging.

2023-12-07 07:27 UTC, Manason approved these changes

2023-12-07 07:27 UTC, Manason commented on config/shared.lua
> +    discordWebhook = nil, -- Replace nil with your webhook if you chose to use discord logging over ox_lib logging
should be a server config only, no? I guess it's fine if you want to keep all config in shared. I see that the target stuff is here as well which would be client only

2023-12-07 07:27 UTC, Manason commented on server/main.lua
> +		logger.log({source = GetInvokingResource(), event = 'hireEmployee', message = string.format('%s | %s hired %s into %s at grade %s', logArea, playerFullName, targetFullName, organizationLabel, grade
Should it be the invoking resource or the string literal 'qbx_management'?

2023-12-07 08:33 UTC, solareon approved these changes

2023-12-07 17:21 UTC, merged