feat: CreateBossZones export and dependencies
Qbox-project/qbx_management pull request #25
Opened 2023-12-08 20:09 UTC by MafewTM

## Description

- Addition of an export for external initiation of the creation of the boss menu zones
- Addition of proper dependencies in the fxmanifest

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-12-08 20:36 UTC, solareon approved these changes

2023-12-08 21:35 UTC, dusan01 approved these changes

2023-12-08 21:37 UTC, MafewTM commented
Don't merge. Let Manason take a look first

2023-12-09 01:45 UTC, Manason requested changes

2023-12-09 01:45 UTC, Manason commented on fxmanifest.lua
> +    'qbx_core',
Don't make an fxmanifest dependency. Use ox_lib

2023-12-09 01:45 UTC, Manason commented on fxmanifest.lua
> +    'ox_lib',
ditto

2023-12-09 01:45 UTC, Manason commented on fxmanifest.lua
> +    'oxmysql',
ditto

2023-12-09 01:45 UTC, Manason commented on client/main.lua
> +exports('CreateBossZones', createBossZones)
Shouldn't this be singular, not plural?

2023-12-09 01:45 UTC, Manason commented on client/main.lua
> +    rotation = rotation or 0.0
Should we move these defaults to be in createZones so that config can make use of them as well?

2023-12-09 01:45 UTC, Manason commented on client/main.lua
> +local function createBossZones(groupName, groupType, coords, size, rotation)
Consider using a table for the parameters. I think the table pattern provides a more readable function call and also allows us to more easily introduce changes in the future without breaking the API

2023-12-11 02:29 UTC, merged