feat: translate pt-br
Qbox-project/qbx_management pull request #61
Opened 2024-05-30 20:31 UTC by mur4i

## Description

[](feat: translate pt-br)

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-06-01 15:51 UTC, mafewtm approved these changes

2024-06-05 15:01 UTC, Manason requested changes
Description does not match the changes

2024-06-15 09:58 UTC, solareon commented
@mur4i did you mean to make a branch with just the locale and accidentally pushed your main?

2024-06-24 01:21 UTC, mur4i commented
yeah maybe i'll try another time

2024-06-24 01:21 UTC, closed without merging